#!/bin/bash

source /home/djeovanz/scriptsUtils/uniUtils/core/dirs/fcSelectDir.sh 
source /home/djeovanz/scriptsUtils/uniUtils/core/dirs/fcGoTodir.sh
source /home/djeovanz/scriptsUtils/uniUtils/core/documents/fcOpenDocuments.sh
source /home/djeovanz/scriptsUtils/uniUtils/core/documents/fcCreateDocuments.sh
source /home/djeovanz/scriptsUtils/uniUtils/core/documents/openDriveDocuments.sh
source /home/djeovanz/scriptsUtils/uniUtils/core/files/fcCopyFiles.sh
source /home/djeovanz/scriptsUtils/uniUtils/core/files/fcSelectFiles.sh
source /home/djeovanz/scriptsUtils/uniUtils/core/documents/fcSynchroniceDocs.sh
source /home/djeovanz/scriptsUtils/uniUtils/core/subjects/fcSubjects.sh
source /home/djeovanz/scriptsUtils/uniUtils/core/utils/fcHelp.sh
source /home/djeovanz/scriptsUtils/uniUtils/core/utils/fcPaths.sh
#fin import source
 
defaultPath=$(cat "$HOME/.config/uniUtils/default_path.txt")
rclonePath="Universidad"
selectedDir=
nameSelectedDir=
sameDir=
dirSelected=
selectedFiles=()

main() {
  # Call checkDefaultPath only if not called with setDefaultPath option
  if [ "$1" != "--setDefaultPath" ] && [ "$1" != "-s" ]; then
    checkDefaultPath
  fi
  clear
  # Check if no arguments are passed
  if [ $# -eq 0 ]; then
      showHelp
  fi
    case "$1" in
      #Registrar una nueva asignatura
      --registerSubject | -rs)
        registerSubject
        ;;

      #Abrir uno o varios documentos
      --openDocuments | -od)
        openDocuments
        ;;
        
      #sincronizar carpeta local con google drive
      --pushFiles | -phf)
        pushFiles
        ;;

      #sincronizar google drive con carpeta local
      --pullFiles | -plf)
        pullFiles
        ;;

      #mandar nueva version de archivos a google drive
      --updateFilesToDrive | -ufd)
        updateFilesToDrive
        ;;

      #traer nueva version de archivos de google drive
      --updateFilesToLocal | -ufl)
        updateFilesToLocal        
        ;;

      #eliminar documentos de local y google drive
      --deleteFiles | -df)
        deleteFiles
        ;;

      #Ir a un directorio
      --goToDir | -gd)
        goToDir
        ;;

      #Agregar documentos a una asignatura
      --addFiles | -af)
      cpFiles
        ;;

      #Crear documentos .docx .xlsx .pptx en una asignatura
      --createFiles | -cf)
        createFiles
        ;;

      # Establecer ruta por defecto donde se registraran las asignaturas
      --setDefaultPath | -s)
        setDefaultPath "$2"
        ;;

      # Muestra la ayuda
      --help | -h)
        showHelp
        exit 0
        ;;
# Invalid option
*)
echo "Invalid option. Try 'uniUtils --help' for more information."
exit 1
;;
esac
shift
}

main "$@"
