#!/bin/bash

source /home/djeovanz/scriptsUtils/uniUtils/core/dirs/fcSelectDir.sh 
source /home/djeovanz/scriptsUtils/uniUtils/core/dirs/fcGoTodir.sh
source /home/djeovanz/scriptsUtils/uniUtils/core/documents/fcOpenDocuments.sh
source /home/djeovanz/scriptsUtils/uniUtils/core/documents/fcCreateDocuments.sh
source /home/djeovanz/scriptsUtils/uniUtils/core/documents/openDriveDocuments.sh
source /home/djeovanz/scriptsUtils/uniUtils/core/files/fcCopyFiles.sh
source /home/djeovanz/scriptsUtils/uniUtils/core/files/fcSelectFiles.sh
source /home/djeovanz/scriptsUtils/uniUtils/core/documents/fcSynchroniceDocs.sh
source /home/djeovanz/scriptsUtils/uniUtils/core/subjects/fcSubjects.sh
source /home/djeovanz/scriptsUtils/uniUtils/core/utils/fcHelp.sh
source /home/djeovanz/scriptsUtils/uniUtils/core/utils/fcPaths.sh
#fin import source
 
defaultPath=$(cat "$HOME/.config/uniUtils/default_path.txt")
rclonePath="Universidad"
selectedDir=
nameSelectedDir=
sameDir=
dirSelected=
selectedFiles=()

main() {
  # Call checkDefaultPath only if not called with setDefaultPath option
  if [ "$1" != "--setDefaultPath" ] && [ "$1" != "-s" ]; then
    checkDefaultPath
  fi
  # clear
  # Check if no arguments are passed
  if [ $# -eq 0 ]; then
    echo "No arguments passed. Try 'uniUtils.sh --help' for more information."
  fi
    case "$1" in
      #Registrar una nueva asignatura
      --registerSubject | -rs)
        registerSubject
        ;;

      #Abri un Documento
      --openDocuments | -od)
        openDocuments
        ;;
        
      #enviar documentos actualizados a google drive
      --pushFiles | -phf)
        pushFiles
        ;;

      #traer documentos actualizados de google drive
      --pullFiles | -plf)
        pullFiles
        ;;

      #eliminar documentos de local y google drive
      --deleteFiles | -df)
        deleteFiles
        ;;

      #Ir a un directorio
      --goToDir | -gd)
        goToDir
        ;;

      #Agregar documentos a una semana examenes o tareas
      --addFiles | -af)
        cpFiles 
        ;;

      --createFiles | -cf)
        createFiles
        ;;

      # Set default path
      --setDefaultPath | -s)
        setDefaultPath "$2"
        ;;

      # Show help
      --help | -h)
        showHelp
        exit 0
        ;;
# Invalid option
*)
echo "Invalid option. Try 'uniUtils --help' for more information."
exit 1
;;
esac
shift
}

main "$@"
