#!/bin/bash

function showHelp {
  echo "Uso: uniUtils [opción] [argumentos]"
  echo ""
  echo "Descripción:"
  echo "Este script tiene como objetivo facilitar la gestión de archivos para estudiantes universitarios."
  echo ""
  echo "Opciones:"
  echo "  --registerSubject | -rs           Registra una nueva asignatura y crea los directorios para sus unidades y semanas."
  echo "  --addFiles | -af                  Mueve documentos a un directorio."
  echo "  --openDocuments | -od             Abre los documentos de un directorio."
  echo "  --createFiles | -cf               Crea un nuevo archivo de Word o Excel y lo copia en la nube de Google Drive."
  echo "  --pushFiles | -phf                Envía documentos actualizados a Google Drive."
  echo "  --pullFiles | -plf                Trae documentos actualizados de Google Drive."
  echo "  --deleteFiles | -df               Elimina documentos de local y Google Drive."
  echo "  --goToDir | -gd                   Va a un directorio."
  echo "  --setDefaultPath | -s <ruta>      Establece la ruta por defecto."
  echo "  --help | -h                       Muestra la ayuda."
  echo ""
  echo "Argumentos:"
  echo "  El comando registerSubject no requiere argumentos adicionales."
  echo "  Para el comando addFiles, se deben seleccionar los archivos a mover y el directorio de destino"
  echo "  Para el comando openDocuments, se deben seleccionar la carpeta y los archivos a abrir."
  echo "  Para el comando createFiles, se deben proporcionar los siguientes argumentos:"
  echo "    fileType                      El tipo de archivo a crear: 1 para Documento de Word, 2 para Hoja de cálculo de Excel."
  echo "                                  Si no se proporciona este argumento, se creará un nuevo Documento de Word por defecto."
  echo "    nameFile                      El nombre del archivo a crear."
  echo "                                  Si no se proporciona este argumento, se utilizará el nombre \"Untitled\" por defecto."
}
